* Infoorg

  Этот текст про организацию информации и поиски подхода к реализации
  персонального информационного менеджера.

  У этого текста есть несколько задач:
    - дать человеку, который заинтересовался вопросом, хотя бы карту и
      ссылки на большие вещи, которые всплывали в обсуждениях вопроса;
    - показать направления решения задачи формата хранения информации,
      на которой все базируется, и которая больше всего тормозит
      процесс развития области;
    - попытаться выработать терминологию и общий язык при описании
      функциональности софта, который регулярно появляется;
    - поговорить про практики, которые стоят за инструментами, потому
      что инструменты создаются для обслуживание практик;
    - вписать вопросы персонального информационного менеджера в
      контекст различной профессиональной деятельности;

  Общая структура текста:
    - немного про область инфоорга;
    - мои практики, под которые нет инструмента;
    - мои идеи про концептуально-интерфейсные части инструмента;
    - RDF как решение для пользовательских онтологий и [[storage-bottle-neck][задачи хранения]];
    - [[history][исторический кусок]] со ссылками на разное в области;
    - [[links][ссылки россыпью]].

  По адресу [[https://teksisto.github.io/infoorg/][teksisto.github.io/infoorg]] всегда лежит самая свежая
  версия. Исходники в формате org-mode лежат в [[https://github.com/teksisto/infoorg][репозитории]] на GitHub.

  Текст можно [[https://github.com/teksisto/infoorg/releases][скачать в формате epub]]. Внутренние ссылки в нем сейчас
  не работают. Под это [[https://github.com/teksisto/infoorg/issues/2][есть issue]]. Пока я делаю его руками, поэтому
  сейчас он обновляется где-то раз в неделю.

  Приходите обсуждать тему и текст в:
  - группу в FreeFeed - https://freefeed.net/infoorg (это такой формат
    между блогом и чатом)
  - канал в телеграме - https://t.me/infoorg

  Вы можете связаться со мной:
  - через телеграмм - https://t.me/teksisto
  - через гуглопочту ~teksisto~
