* Scratch

  Здесь лежат куски текста, которым еще не нашлось место в основном
  тексте.

** Базовые определения

*** Ресурс

    Отдельная сущность, адресуемая уникальным идентификатором. Роль
    идентификатора выполняет URI.

    Имеет множество атрибутов в формате ключ=значение.

    Имеет множество представлений.

    Ресурс имеет класс, который определяет его базовый логический
    тип. Класс определяет какие атрибуты можно вешать на этот ресурс и
    с помощью каких представлений его рисовать.

    Идентификатор позволяет выцепить из источника данных настоящий
    контент, соответствующий ресурсу. Это так называемый dereferencing.

    Контент есть только у неделимых ресурсов, то есть на самом деле не
    у всех. Контент есть у ресурса, являющегося параграфом текста,
    картинкой, аудио-файлом, видео-файлом. Для ресурсов, у которых нет
    контента, устанавливается некий пустой адаптер.

*** Представление

    У ресурса есть класс. Классу соответствует множество представлений,
    из которого выбирается нужное. Представление – это шаблон, который
    получает на входе ресурс, достает из него хеш с атрибутами, с
    помощью адаптера получает контент и рисует из всего этого html.

    У одного ресурса есть множество представлений.

    Три стандартных, которые показывают ресурс вне зависимости от того
    есть у него класс или нет:

    1) ~default~ – показывает атрибуты и контент. Атрибуты содержащие
       ссылки на другие ресурсы показываются просто ссылками и никак не
       отображаются.
    2) ~inline~ – показывает только контент. Для параграфа это текст в
       теге ~<p>~, для картинки тег ~<img>~ и так далее.
    2) ~link~ – показывает только ссылку на ресурс.

    Расширенные, опирающиеся на класс:

    1) ~classed-link~ – отображает иконку рядом со ссылкой в зависимости
       от типа ресурса.
    2) ~card~ – показывает некоторую компактную summary по ресурсу и
       ссылку на полную версию. Например для книги это может быть
       обложка, под которой написано полное название и год
       издания. Карточки используются при отображении "плитки" из
       ресурсов.
    3) ~classed-link-with-card~ – ~classed-link~ у которой при навении
       мышки на ссылку появляется карточка во всплывающем окне.

*** Атрибут

    Атрибут тоже ресурс. На него тоже можно навешивать атрибуты.

    Адаптер для него HTTP, потому что так сложилось.

    Формат атрибута ~<attribute>=<value>~. UUID ресурса плюс ключ и значение
    образовывают триплет.

*** Адаптер

    URI состоит из NID и NSS.

    NID – namespace id. Позволяет выбрать адаптер для совершения с ресурсом базовых
    действий.

    NSS – namespace spicific string. Позволяет однозначно ссылаться на
    ресурс внутри определенного namespace.

    Основные действия, которые должен поддерживать ресурс:

    - создание
    - чтение
    - редактирование
    - удаление

    Действия над метаданными внутри ресурса:

    - добавить единицу метаданных в формате ключ=значение
    - вернуть значение по определенному ключу
    - считать все метаданные и вернуть хеш
    - установить значение по определенному ключу
    - удалить единицу метаданных по ключу

    Некоторые ресурсы могут не поддерживать метаданные (plain text) или
    быть недоступными для удаления/редактирование (страница в
    интернете). В этом случае адаптер просто не поддерживает эти
    операции.
